services:
  user:
    build: ./web
    container_name: user
    ports:
      - "8001:8001"
    networks:
      - app-network

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "8002:8002"
    depends_on:
      - user
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
